import { NextRequest, NextResponse } from 'next/server';
import { npsFetch, npsConfig } from '@/utils/npsConfig';

// Define response shape for NPS transaction status
interface NpsStatusResponse {
  code: string;
  message: string;
  data: any;
}
export async function POST(request: NextRequest) {
    try {
        const body = await request.json();
        const { merchantTxnId } = body;

        if (!merchantTxnId) {
            return NextResponse.json(
                { success: false, error: 'Missing merchantTxnId' },
                { status: 400 }
            );
        }

        console.log(`🔍 [NPS-CHECK-STATUS] Checking status for: ${merchantTxnId}`);

        const statusRequest = {
            MerchantId: npsConfig.merchantId,
            MerchantName: npsConfig.merchantName,
            MerchantTxnId: merchantTxnId,
            Signature: "" // Will be generated by interceptor
        };

        const statusResponse = await npsFetch<NpsStatusResponse>(
            '/CheckTransactionStatus',
            statusRequest
        );

        console.log('✅ [NPS-CHECK-STATUS] Response:', statusResponse.data);

        if (statusResponse.data.code !== "0") {
            return NextResponse.json({
                success: false,
                error: statusResponse.data.message
            }, { status: 400 });
        }

        return NextResponse.json({
            success: true,
            data: statusResponse.data.data
        });

    } catch (error: any) {
        console.error('❌ [NPS-CHECK-STATUS] Error:', error);
        return NextResponse.json(
            { success: false, error: error.message },
            { status: 500 }
        );
    }
}
