import type { NextApiRequest, NextApiResponse } from 'next';
import { npsClient, npsConfig } from '../../utils/npsConfig';
import { fetchDataFromApi, updateUserBagWithPayment } from '../../utils/api';
const { generateLocalTimestamp } = require('../../utils/timezone');
import type { 
  NPSWebhookPayload, 
  NPSPaymentData,
  CheckTransactionStatusRequest,
  CheckTransactionStatusResponse
} from '../../types/nps';

export default async function handler(
  req: NextApiRequest,
  res: NextApiResponse
) {
  // NPS sends GET requests with query parameters for webhook notifications
  if (req.method !== 'GET') {
    console.error('Invalid method:', req.method);
    res.writeHead(405, { 'Content-Type': 'text/plain' });
    res.end('Method not allowed');
    return;
  }

  try {
    console.log('=== NPS WEBHOOK RECEIVED ===');
    console.log('Query params:', req.query);
    console.log('Headers:', req.headers);

    const { MerchantTxnId, GatewayTxnId } = req.query;

    // Validate required parameters
    if (!MerchantTxnId || !GatewayTxnId) {
      console.error('Missing required webhook parameters');
      res.writeHead(400, { 'Content-Type': 'text/plain' });
      res.end('Missing required parameters');
      return;
    }

    const merchantTxnId = MerchantTxnId as string;
    const gatewayTxnId = GatewayTxnId as string;

    console.log(`Processing webhook for merchant transaction: ${merchantTxnId}, gateway transaction: ${gatewayTxnId}`);

    // STEP 1: Verify transaction status with NPS (as per documentation)
    console.log('=== VERIFYING TRANSACTION WITH NPS ===');
    const statusRequest: CheckTransactionStatusRequest = {
      MerchantId: npsConfig.merchantId,
      MerchantName: npsConfig.merchantName,
      MerchantTxnId: merchantTxnId,
      Signature: "" // Will be generated by interceptor
    };

    const statusResponse = await npsClient.post<CheckTransactionStatusResponse>(
      '/CheckTransactionStatus',
      statusRequest
    );

    console.log('NPS Transaction verification response:', statusResponse.data);

    if (statusResponse.data.code !== "0") {
      console.error('Transaction verification failed with NPS:', statusResponse.data);
      res.writeHead(400, { 'Content-Type': 'text/plain' });
      res.end('Transaction verification failed');
      return;
    }

    const transactionData = statusResponse.data.data;
    console.log('✅ Transaction verified with NPS:', {
      status: transactionData.Status,
      amount: transactionData.Amount,
      gatewayRef: transactionData.GatewayReferenceNo
    });

    // STEP 2: Find the user who made this payment by searching user bags
    console.log('=== FINDING USER BY PAYMENT ===');
    console.log('Searching for payment with merchant transaction ID:', merchantTxnId);
    
    try {
      // Search for user bags that contain this payment
      const userBagsResponse = await fetchDataFromApi(
        `/api/user-bags?populate=*`
      );

      if (!userBagsResponse?.data || userBagsResponse.data.length === 0) {
        console.error('⚠️ No user bags found in system');
        console.log('✅ Transaction verified with NPS but no user bags found');
        console.log('Acknowledging webhook to prevent retries');
        
        res.writeHead(200, { 'Content-Type': 'text/plain' });
        res.end('received');
        return;
      }

      // Find the user bag that contains this payment
      let targetUserBag: any = null;
      for (const bag of userBagsResponse.data) {
        if (bag.user_orders?.payments) {
          const payment = bag.user_orders.payments.find((p: any) => 
            p.merchantTxnId === merchantTxnId || 
            p.gatewayReferenceNo === transactionData.GatewayReferenceNo
          );
          if (payment) {
            targetUserBag = bag;
            console.log('✅ Found payment in user bag:', bag.documentId);
            break;
          }
        }
      }

      if (!targetUserBag) {
        console.error('⚠️ Payment not found in any user bag:', merchantTxnId);
        console.log('✅ Transaction verified with NPS but payment not found in user bags');
        console.log('Acknowledging webhook to prevent retries');
        
        res.writeHead(200, { 'Content-Type': 'text/plain' });
        res.end('received');
        return;
      }

      // STEP 3: Check if this transaction has already been processed
      const existingPayments = targetUserBag.user_orders?.payments || [];
      const existingPayment = existingPayments.find((payment: any) => 
        payment.merchantTxnId === merchantTxnId && payment.webhook_processed === true
      );

      if (existingPayment) {
        console.log('✅ Transaction already processed by webhook:', merchantTxnId);
        console.log('Response details: status=200, content-type=text/plain, body="already received"');
        
        res.writeHead(200, { 'Content-Type': 'text/plain' });
        res.end('already received');
        return;
      }

      // STEP 4: Save payment data to user-bag
      console.log('=== SAVING PAYMENT DATA ===');
      const paymentData: NPSPaymentData = {
        provider: "nps",
        processId: transactionData.ProcessId,
        merchantTxnId: transactionData.MerchantTxnId,
        gatewayReferenceNo: transactionData.GatewayReferenceNo,
        amount: parseFloat(transactionData.Amount),
        status: transactionData.Status,
        transactionDate: transactionData.TransactionDate,
        institution: transactionData.Institution,
        instrument: transactionData.Instrument,
        serviceCharge: transactionData.ServiceCharge,
        cbsMessage: transactionData.CbsMessage,
        timestamp: generateLocalTimestamp(),
        webhook_processed: true, // Flag to indicate this came from webhook
      };

      await updateUserBagWithPayment(targetUserBag.documentId, paymentData);
      
      console.log('✅ Webhook payment data saved successfully:', paymentData);

    } catch (dbError: any) {
      console.error('⚠️ Database error during webhook processing:', dbError);
      console.log('✅ Transaction verified with NPS but database operation failed');
      console.log('Acknowledging webhook to prevent retries');
    }

    // STEP 5: Always acknowledge the webhook to NPS
    // NPS expects plain text response "received" for first time
    console.log('✅ Sending acknowledgment to NPS');
    console.log('Response details: status=200, content-type=text/plain, body="received"');
    
    // Ensure we're sending plain text response exactly as NPS expects
    res.writeHead(200, { 'Content-Type': 'text/plain' });
    res.end('received');
    return;

  } catch (error: any) {
    console.error('❌ Webhook processing error:', error);
    console.error('Error stack:', error.stack);
    
    // Even if there's an error, we should acknowledge to prevent infinite retries
    // unless it's a critical NPS verification error
    if (error.response?.status === 401 || error.response?.status === 403) {
      console.error('❌ NPS authentication error - not acknowledging');
      res.writeHead(500, { 'Content-Type': 'text/plain' });
      res.end('Authentication error');
      return;
    }
    
    console.log('⚠️ Error occurred but acknowledging webhook to prevent retries');
    res.writeHead(200, { 'Content-Type': 'text/plain' });
    res.end('received');
    return;
  }
} 